### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by coingraham**
Fixing typo in the url reference.

*Issue #, if available:*

*Description of changes: fixing typo.*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by randyurbano** [comment]
The typo is fixed in the current file.

**Comment by coingraham** [comment]
Did I make a mistake with submission?

**Comment by randyurbano** [comment]
No mistake. Our documentation team corrected the typo in the source file and updated the file here. Thanks again for your feedback.

**Comment by coingraham** [comment]
Will this be the strategy going forward?  (i.e. Will all updates be rejected by the user and updated by the team manually?)

**Comment by randyurbano** [comment]
No, sorry, I did make a mistake. I should have merged your changes. I will do that for new pull requests that are accepted. Again, I am sorry about the confusion. This is a new process for our team.

**Pull request closed without merging**
